#!/usr/bin/env python3
"""
Draws the routes from a *_routes.csv file generated by the GLIMS simulator as GeoJSON files ready to be loaded into QGIS (one line layer + one point layer).

Resolves each stop in the stop_sequence column to real-world coordinates:

* direct_delivery / cycling_last_mile / walking_last_mile /
  customer_collection  ->  labels are ``customer_id`` values and are looked
  up in the demand file (results/<city>/demand/demand_<sc>_<size>.csv).
* facility_supply  ->  labels are facility ``Location`` names and are looked
  up in records_classified.csv / centros_cc.csv.

The depot (the origin/end point of each round-trip route) is taken from the depot column:

* direct_delivery / facility_supply  ->  logistics center (centros_cc.csv)
* last-mile legs                     ->  microhub / PUDO (records_classified)

The geometry is obtained from the OSRM /route service (using the actual road network), using the appropriate profile port based on vehicle_type. If OSRM fails and the fallback is not disabled, a straight line is drawn between the stops.

Examples

List the routes available in a file:

python -m code.viz.draw_routes path/to/m3_routes.csv --list

Draw a specific route:

python -m code.viz.draw_routes path/to/m1_routes.csv \
    --route-id "M1_l'Eixample_direct_delivery_DCT9 Amazon Logistics_1"

Draw all routes in the file:

python -m code.viz.draw_routes path/to/m3_routes.csv --all

Resolve synthetic facilities (facility_6, ...) using an override file:

python -m code.viz.draw_routes path/to/m3_routes.csv --all \
    --facility-coords my_facilities.csv
# my_facilities.csv: name,lat,lon

The script is intended to be run from the project root (so that the code.* imports work), for example with:

python -m code.viz.draw_routes ...

after placing this file in code/viz/. It can also be run independently by providing --data-dir and --results-dir.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import pandas as pd

try:
    import requests
except ImportError:  # pragma: no cover
    requests = None

try:
    from code.common.paths import DATA_DIR as _PROJECT_DATA_DIR
    from code.common.paths import RESULTS_DIR as _PROJECT_RESULTS_DIR
except Exception:  # pragma: no cover
    _PROJECT_DATA_DIR = None
    _PROJECT_RESULTS_DIR = None

try:
    from code.common.constants import OSRM_PORTS as _PROJECT_OSRM_PORTS
except Exception:  # pragma: no cover
    _PROJECT_OSRM_PORTS = None


VEHICLE_PROFILE = {
    "conventional_van": "driving",
    "electric_van": "driving",
    "cargo_bike": "cycling",
    "walking_courier": "walking",
    "customer_walking": "walking",
}

CUSTOMER_LEGS = {
    "direct_delivery",
    "cycling_last_mile",
    "walking_last_mile",
    "customer_collection",
}

FACILITY_LEGS = {"facility_supply"}
CC_DEPOT_LEGS = {"direct_delivery", "facility_supply"}
STOP_SEPARATOR = " -> "



def parse_experiment_id(experiment_id: str) -> tuple[str, int]:
    """Extracts (scenario, instance_size) from an experiment_id."""
    match = re.search(r"_(low|medium|high)_(\d+)_", str(experiment_id))
    if not match:
        raise ValueError(
            f"Could not extract scenario and size from experiment_id "
            f"'{experiment_id}'. Pass them with --scenario and --instance-size."
        )
    return match.group(1), int(match.group(2))


def load_demand_map(
    results_dir: Path, city: str, scenario: str, size: int
) -> dict[str, tuple[float, float]]:
    """customer_id (str) -> (lon, lat) from the demand file."""
    path = results_dir / city / "demand" / f"demand_{scenario}_{size}.csv"
    if not path.exists():
        raise FileNotFoundError(f"Demand file does not exist: {path}")
    df = pd.read_csv(path)
    lon_col = "lon" if "lon" in df.columns else "Longitude"
    lat_col = "lat" if "lat" in df.columns else "Latitude"
    mapping: dict[str, tuple[float, float]] = {}
    for _, row in df.iterrows():
        cid = str(row["customer_id"]).strip()
        mapping[cid] = (float(row[lon_col]), float(row[lat_col]))
    return mapping


def _add_names_from_dataframe(
    df: pd.DataFrame, gazetteer: dict[str, tuple[float, float]]
) -> None:
    """Adds name->(lon,lat) using any text column of the DataFrame.

    We don't know for sure the exact name of the name column in
    records_classified.csv, so we index by all text columns
    so that lookup works no matter what it's called.
    """
    lat_col = next((c for c in ("Latitude", "lat", "latitude") if c in df.columns), None)
    lon_col = next((c for c in ("Longitude", "lon", "longitude") if c in df.columns), None)
    if lat_col is None or lon_col is None:
        return
    text_cols = [c for c in df.columns if df[c].dtype == object]
    for _, row in df.iterrows():
        try:
            coord = (float(row[lon_col]), float(row[lat_col]))
        except (TypeError, ValueError):
            continue
        for col in text_cols:
            value = row[col]
            if isinstance(value, str):
                key = value.strip()
                if key and key not in gazetteer:
                    gazetteer[key] = coord


def load_facility_gazetteer(
    results_dir: Path,
    data_dir: Path,
    city: str,
    override_path: Path | None,
) -> dict[str, tuple[float, float]]:
    """Dictionary name -> (lon, lat) for logistics centers, microhubs and PUDOs."""
    gazetteer: dict[str, tuple[float, float]] = {}

    centers_path = data_dir / city / "centros_cc.csv"
    if centers_path.exists():
        _add_names_from_dataframe(pd.read_csv(centers_path), gazetteer)
    else:
        print(f"[warning] centros_cc.csv not found at {centers_path}", file=sys.stderr)

    classified_path = (
        results_dir / city / "location_review" / "records_classified.csv"
    )
    if classified_path.exists():
        _add_names_from_dataframe(pd.read_csv(classified_path), gazetteer)
    else:
        print(
            f"[warning] records_classified.csv not found at {classified_path}",
            file=sys.stderr,
        )

    # Manual override (for facility_6 and other synthetic names).
    if override_path is not None:
        if not override_path.exists():
            raise FileNotFoundError(f"Override file does not exist: {override_path}")
        odf = pd.read_csv(override_path)
        name_col = next((c for c in ("name", "Name", "Location") if c in odf.columns), None)
        lat_col = next((c for c in ("lat", "Latitude") if c in odf.columns), None)
        lon_col = next((c for c in ("lon", "Longitude") if c in odf.columns), None)
        if not (name_col and lat_col and lon_col):
            raise ValueError(
                "The --facility-coords CSV needs name, lat, lon columns."
            )
        for _, row in odf.iterrows():
            gazetteer[str(row[name_col]).strip()] = (
                float(row[lon_col]),
                float(row[lat_col]),
            )

    return gazetteer



def resolve_osrm_ports(city: str, override: str | None) -> dict[str, int]:
    """Returns {profile: port} for the city."""
    if override:
        ports: dict[str, int] = {}
        for pair in override.split(","):
            profile, _, port = pair.partition("=")
            ports[profile.strip()] = int(port)
        return ports
    if _PROJECT_OSRM_PORTS and city in _PROJECT_OSRM_PORTS:
        return dict(_PROJECT_OSRM_PORTS[city])
    raise RuntimeError(
        "Could not determine the OSRM ports. Run from the project root "
        "or pass them with --osrm-ports 'driving=5000,cycling=5001,"
        "walking=5002'."
    )


def osrm_route_geometry(
    coords: list[tuple[float, float]], profile: str, port: int
) -> list[list[float]]:
    """Asks OSRM for the street geometry through coords in order."""
    if requests is None:
        raise RuntimeError("The 'requests' package is not available.")
    coord_str = ";".join(f"{lon:.6f},{lat:.6f}" for lon, lat in coords)
    url = f"http://localhost:{port}/route/v1/{profile}/{coord_str}"
    params = {"overview": "full", "geometries": "geojson", "continue_straight": "false"}
    response = requests.get(url, params=params, timeout=60)
    response.raise_for_status()
    payload = response.json()
    if payload.get("code") != "Ok" or not payload.get("routes"):
        raise RuntimeError(
            f"OSRM /route error: {payload.get('code')} - {payload.get('message', '')}"
        )
    return payload["routes"][0]["geometry"]["coordinates"]



def resolve_stops(
    labels: list[str],
    leg: str,
    demand_map: dict[str, tuple[float, float]],
    gazetteer: dict[str, tuple[float, float]],
) -> tuple[list[tuple[float, float]], list[str], list[str]]:
    """Returns (resolved_coords, resolved_labels, unresolved_labels)."""
    coords: list[tuple[float, float]] = []
    resolved: list[str] = []
    missing: list[str] = []
    use_demand = leg in CUSTOMER_LEGS
    for label in labels:
        key = label.strip()
        coord = None
        if use_demand:
            coord = demand_map.get(key)
            if coord is None:
                try:
                    coord = demand_map.get(str(int(key)))
                except ValueError:
                    coord = None
        else:
            coord = gazetteer.get(key)
        if coord is None:
            missing.append(key)
        else:
            coords.append(coord)
            resolved.append(key)
    return coords, resolved, missing


def resolve_depot(
    depot_name: str,
    leg: str,
    gazetteer: dict[str, tuple[float, float]],
) -> tuple[float, float] | None:
    """The depot is always a name (logistics center or facility): looked up in the gazetteer."""
    return gazetteer.get(str(depot_name).strip())


def build_route_features(
    row: pd.Series,
    demand_map: dict[str, tuple[float, float]],
    gazetteer: dict[str, tuple[float, float]],
    osrm_ports: dict[str, int],
    geometry_mode: str,
    fallback_straight: bool,
) -> tuple[list[dict], list[dict], list[str]]:
    """Generates line and point features for a route row."""
    warnings: list[str] = []
    leg = str(row["leg"])
    vehicle_type = str(row["vehicle_type"])
    depot_name = str(row["depot"])
    route_id = str(row["route_id"])
    profile = VEHICLE_PROFILE.get(vehicle_type, "driving")

    labels = [
        part.strip()
        for part in str(row["stop_sequence"]).split(STOP_SEPARATOR)
        if part.strip()
    ]
    stop_coords, resolved_labels, missing = resolve_stops(
        labels, leg, demand_map, gazetteer
    )
    if missing:
        warnings.append(
            f"{route_id}: {len(missing)} stop(s) without coordinates: "
            f"{', '.join(missing[:5])}{'...' if len(missing) > 5 else ''}"
        )

    depot_coord = resolve_depot(depot_name, leg, gazetteer)
    if depot_coord is None:
        warnings.append(
            f"{route_id}: depot '{depot_name}' has no coordinates "
            f"(synthetic name? use --facility-coords)."
        )

    if not stop_coords:
        warnings.append(f"{route_id}: no resolvable stops, skipping the line.")
        return [], [], warnings

    ordered = []
    if depot_coord is not None:
        ordered.append(depot_coord)
    ordered.extend(stop_coords)
    if depot_coord is not None:
        ordered.append(depot_coord)

    geometry_source = geometry_mode
    if geometry_mode == "osrm":
        try:
            line_coords = osrm_route_geometry(ordered, profile, osrm_ports[profile])
        except Exception as exc:  # OSRM down or one-off error
            if fallback_straight:
                warnings.append(f"{route_id}: OSRM failed ({exc}); straight line.")
                line_coords = [[lon, lat] for lon, lat in ordered]
                geometry_source = "straight_fallback"
            else:
                warnings.append(f"{route_id}: OSRM failed ({exc}); line skipped.")
                line_coords = None
    else:
        line_coords = [[lon, lat] for lon, lat in ordered]

    line_features: list[dict] = []
    if line_coords is not None:
        line_features.append(
            {
                "type": "Feature",
                "geometry": {"type": "LineString", "coordinates": line_coords},
                "properties": {
                    "route_id": route_id,
                    "model": str(row.get("model", "")),
                    "leg": leg,
                    "vehicle_type": vehicle_type,
                    "profile": profile,
                    "depot": depot_name,
                    "geometry_source": geometry_source,
                    "stop_count": _safe(row, "stop_count"),
                    "distance_km": _safe(row, "distance_km"),
                    "duration_min": _safe(row, "duration_min"),
                    "package_load": _safe(row, "package_load"),
                    "routing_algorithm": str(row.get("routing_algorithm", "")),
                    "experiment_id": str(row.get("experiment_id", "")),
                },
            }
        )

    point_features: list[dict] = []
    if depot_coord is not None:
        point_features.append(
            _point_feature(
                depot_coord, depot_name, "depot", 0, route_id, row, leg, vehicle_type
            )
        )
    for order, (coord, label) in enumerate(zip(stop_coords, resolved_labels), start=1):
        point_features.append(
            _point_feature(
                coord, label, "stop", order, route_id, row, leg, vehicle_type
            )
        )

    return line_features, point_features, warnings


def _point_feature(coord, label, kind, order, route_id, row, leg, vehicle_type) -> dict:
    lon, lat = coord
    return {
        "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [lon, lat]},
        "properties": {
            "label": label,
            "kind": kind,
            "visit_order": order,
            "route_id": route_id,
            "model": str(row.get("model", "")),
            "leg": leg,
            "vehicle_type": vehicle_type,
        },
    }


def _safe(row: pd.Series, column: str):
    value = row.get(column)
    if pd.isna(value):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return value



def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Draws GLIMS simulator routes as GeoJSON for QGIS."
    )
    parser.add_argument("routes_file", type=Path, help="Path to the *_routes.csv file")
    selection = parser.add_mutually_exclusive_group()
    selection.add_argument(
        "--route-id", action="append", default=None,
        help="route_id to draw (repeatable).",
    )
    selection.add_argument("--all", action="store_true", help="Draw all routes.")
    parser.add_argument("--list", action="store_true", help="List route_ids and exit.")
    parser.add_argument(
        "--geometry", choices=("osrm", "straight"), default="osrm",
        help="Line geometry (default: osrm).",
    )
    parser.add_argument(
        "--no-fallback-straight", action="store_true",
        help="Do not fall back to a straight line if OSRM fails.",
    )
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--output-prefix", default=None)
    parser.add_argument("--data-dir", type=Path, default=None)
    parser.add_argument("--results-dir", type=Path, default=None)
    parser.add_argument("--scenario", choices=("low", "medium", "high"), default=None)
    parser.add_argument("--instance-size", type=int, default=None)
    parser.add_argument(
        "--facility-coords", type=Path, default=None,
        help="CSV name,lat,lon to resolve synthetic facilities (facility_N).",
    )
    parser.add_argument(
        "--osrm-ports", default=None,
        help="Port override: 'driving=5000,cycling=5001,walking=5002'.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()

    data_dir = args.data_dir or _PROJECT_DATA_DIR
    results_dir = args.results_dir or _PROJECT_RESULTS_DIR
    if data_dir is None or results_dir is None:
        raise SystemExit(
            "Could not determine DATA_DIR / RESULTS_DIR. Run from the project "
            "root or pass --data-dir and --results-dir."
        )
    data_dir = Path(data_dir)
    results_dir = Path(results_dir)

    if not args.routes_file.exists():
        raise SystemExit(f"Routes file does not exist: {args.routes_file}")
    routes_df = pd.read_csv(args.routes_file)
    if routes_df.empty:
        raise SystemExit("The routes file is empty.")

    if args.list:
        print(f"Routes available in {args.routes_file.name}:")
        for _, row in routes_df.iterrows():
            print(
                f"  [{row.get('model', '?')}/{row.get('leg', '?')}] "
                f"{row['route_id']}"
            )
        return

    if args.route_id:
        selected = routes_df[routes_df["route_id"].isin(args.route_id)]
        if selected.empty:
            raise SystemExit(
                "No route_id matched. Use --list to see the available ones."
            )
    elif args.all:
        selected = routes_df
    else:
        raise SystemExit(
            "Specify what to draw: --route-id <id> (repeatable) or --all "
            "(or --list to see the options)."
        )

    city = str(routes_df.iloc[0]["city"]).strip()
    if args.scenario and args.instance_size:
        scenario, size = args.scenario, args.instance_size
    else:
        experiment_id = str(routes_df.iloc[0]["experiment_id"])
        scenario, size = parse_experiment_id(experiment_id)

    print(f"City={city} | scenario={scenario} | size={size}", file=sys.stderr)

    demand_map = load_demand_map(results_dir, city, scenario, size)
    gazetteer = load_facility_gazetteer(
        results_dir, data_dir, city, args.facility_coords
    )
    osrm_ports = (
        resolve_osrm_ports(city, args.osrm_ports)
        if args.geometry == "osrm"
        else {}
    )

    all_lines: list[dict] = []
    all_points: list[dict] = []
    all_warnings: list[str] = []
    for _, row in selected.iterrows():
        lines, points, warnings = build_route_features(
            row,
            demand_map,
            gazetteer,
            osrm_ports,
            args.geometry,
            not args.no_fallback_straight,
        )
        all_lines.extend(lines)
        all_points.extend(points)
        all_warnings.extend(warnings)

    output_dir = args.output_dir or args.routes_file.parent
    output_dir.mkdir(parents=True, exist_ok=True)
    prefix = args.output_prefix or args.routes_file.stem
    lines_path = output_dir / f"{prefix}_lines.geojson"
    points_path = output_dir / f"{prefix}_points.geojson"

    _write_geojson(lines_path, all_lines)
    _write_geojson(points_path, all_points)

    print(
        f"\nDone: {len(all_lines)} line(s), {len(all_points)} point(s).",
        file=sys.stderr,
    )
    print(f"  Lines: {lines_path}", file=sys.stderr)
    print(f"  Points: {points_path}", file=sys.stderr)
    if all_warnings:
        print(f"\n{len(all_warnings)} warning(s):", file=sys.stderr)
        for warning in all_warnings:
            print(f"  - {warning}", file=sys.stderr)


def _write_geojson(path: Path, features: list[dict]) -> None:
    collection = {
        "type": "FeatureCollection",
        "crs": {"type": "name", "properties": {"name": "urn:ogc:def:crs:OGC:1.3:CRS84"}},
        "features": features,
    }
    path.write_text(json.dumps(collection, ensure_ascii=False), encoding="utf-8")


if __name__ == "__main__":
    main()