from __future__ import annotations

CITIES = [
    "barcelona",
    "madrid",
    "valencia",
]

EARTH_RADIUS_METERS = 6_371_000

# Canonical service-type codes generated by review_b2c_locations.py.
UNKNOWN_SERVICE_TYPE_CODE = 0
LOCKER_SERVICE_TYPE_CODE = 1
PUDO_SERVICE_TYPE_CODE = 2
CLICK_COLLECT_SERVICE_TYPE_CODE = 3
DISTRIBUTION_CENTER_SERVICE_TYPE_CODE = 4
LAST_MILE_STATION_SERVICE_TYPE_CODE = 5
WAREHOUSE_SERVICE_TYPE_CODE = 6
CONVENIENCE_STORE_SERVICE_TYPE_CODE = 7


# Facilities that can act as the main logistics origin.
ORIGIN_FACILITY_CODES = frozenset(
    {
        DISTRIBUTION_CENTER_SERVICE_TYPE_CODE,
        WAREHOUSE_SERVICE_TYPE_CODE,
    }
)


# Facilities that can act as last-mile intermediate stations.
MICROHUB_FACILITY_CODES = frozenset(
    {
        LAST_MILE_STATION_SERVICE_TYPE_CODE,
    }
)


# Facilities where parcels may be delivered or collected.
PUDO_FACILITY_CODES = frozenset(
    {
        LOCKER_SERVICE_TYPE_CODE,
        PUDO_SERVICE_TYPE_CODE,
        CLICK_COLLECT_SERVICE_TYPE_CODE,
        CONVENIENCE_STORE_SERVICE_TYPE_CODE,
    }
)