from __future__ import annotations

CITIES = ["barcelona","madrid","valencia"]

EARTH_RADIUS_METERS = 6_371_000

# Canonical service-type codes generated by review_b2c_locations.py.
UNKNOWN_SERVICE_TYPE_CODE = 0
LOCKER_SERVICE_TYPE_CODE = 1
PUDO_SERVICE_TYPE_CODE = 2
CLICK_COLLECT_SERVICE_TYPE_CODE = 3
DISTRIBUTION_CENTER_SERVICE_TYPE_CODE = 4
LAST_MILE_STATION_SERVICE_TYPE_CODE = 5
WAREHOUSE_SERVICE_TYPE_CODE = 6
CONVENIENCE_STORE_SERVICE_TYPE_CODE = 7


# Facilities that can act as the main logistics origin.
ORIGIN_FACILITY_CODES = frozenset(
    {
        DISTRIBUTION_CENTER_SERVICE_TYPE_CODE,
        WAREHOUSE_SERVICE_TYPE_CODE,
    }
)


# Facilities that can act as last-mile intermediate stations.
MICROHUB_FACILITY_CODES = frozenset(
    {
        LAST_MILE_STATION_SERVICE_TYPE_CODE,
    }
)


# Facilities where parcels may be delivered or collected.
PUDO_FACILITY_CODES = frozenset(
    {
        LOCKER_SERVICE_TYPE_CODE,
        PUDO_SERVICE_TYPE_CODE,
        CLICK_COLLECT_SERVICE_TYPE_CODE,
        CONVENIENCE_STORE_SERVICE_TYPE_CODE,
    }
)

SERVICE_TIME_PER_STOP_MIN = 5.0

OSRM_PORTS = {
    "madrid": {
        "driving": 5000,
        "cycling": 5001,
        "walking": 5002,
    },
    "barcelona": {
        "driving": 5010,
        "cycling": 5011,
        "walking": 5012,
    },
    "valencia": {
        "driving": 5020,
        "cycling": 5021,
        "walking": 5022,
    },
}

MAX_ROUTE_DURATION_MIN = 480.0

DIRECT_VAN_LOADING_TIME_PER_ROUTE_MIN = 15.0
TRUCK_LOADING_TIME_PER_ROUTE_MIN = 15.0
BIKE_PREPARATION_TIME_PER_ROUTE_MIN = 5.0
WALKING_PREPARATION_TIME_PER_ROUTE_MIN = 5.0

OSRM_PROBE_COORDS = {
    "madrid": [(-3.703790, 40.416775), (-3.693790, 40.426775)],
    "barcelona": [(2.173404, 41.385064), (2.183404, 41.395064)],
    "valencia": [(-0.376288, 39.469907), (-0.366288, 39.479907)],
}

OSRM_TABLE_BLOCK_SIZE = 200
OSRM_TABLE_MIN_BLOCK_SIZE = 25